version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@3.1.5
  

jobs:
  cliInstall:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: ubuntu 
      - persist_to_workspace:
          root: .
          paths:
            - .
  Update:
    machine:
        image: ubuntu-2204:2023.04.2
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./build s3://logixpro-wms
    

workflows:
  EC2-Deploy:
    jobs:
      - cliInstall
      - Update:
          requires:
            - cliInstall