version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@3.0.0
  aws-cli: circleci/aws-cli@3.1.5
  

jobs:
  s3Deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: ubuntu
      - run: zip -r WMS_LogixPro.zip . && aws s3 cp WMS_LogixPro.zip s3://logixpro-wms
      - persist_to_workspace:
          root: .
          paths:
            - .
  codeDeploy:
    machine:
        image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - aws-code-deploy/deploy:
          application-name: s3_circleci
          auth:
            - aws-cli/setup
          bundle-bucket: logixpro-wms
          bundle-key: WMS_LogixPro.zip
          deployment-group: s3_circleci_group

    

workflows:
  EC2-Deploy:
    jobs:
      - s3Deploy
      - codeDeploy:
          requires:
            - s3Deploy