version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@3.1.5
  

jobs:
  build:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: b4rz
      - run: cd ./home/ubuntu/WMS_Front-end && npm install && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: ubuntu-2204:2023.04.2
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./build s3://logixpro-frontend
    

workflows:
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main