version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  aws-code-deploy: circleci/aws-code-deploy@3.0.0
  

jobs:
  s3Deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: ubuntu
      - run: zip -r WMS_LogixPro.zip . && aws s3 cp WMS_LogixPro.zip s3://logixpro-wms
      - persist_to_workspace:
          root: .
          paths:
            - .
  codeDeploy:
    machine:
        image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run: |
          aws deploy create-deployment \
            --application-name s3_circle_ci \
            --deployment-group-name s3_circle_group \
            --file-exists-behavior OVERWRITE \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location s3://logixpro-wms/WMS_LogixPro.zip \

    

workflows:
  EC2-Deploy:
    jobs:
      - s3Deploy
      - codeDeploy:
          requires:
            - s3Deploy