version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  aws-code-deploy: circleci/aws-code-deploy@3.0.0
  

jobs:
  codeDeploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: b4rz
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run: |
            COMMIT_ID=$(curl -s https://api.github.com/repos/WMS-PF/WMS_LogixPro/commits/circleci-and-codedeploy-setup | jq -r '.sha')
            aws deploy create-deployment \
              --application-name github_dep \
              --deployment-group-name github_dep_group \
              --file-exists-behavior OVERWRITE \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --github-location repository=WMS-PF/WMS_LogixPro,commitId=$COMMIT_ID \
  codeDeploy2:
      executor: aws-cli/default
      steps:
        - checkout
        - aws-cli/setup:
            profile-name: andresF
            aws-access-key-id: AWS_ACCESS_KEY_ID_1
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY_1
        - run: |
            COMMIT_ID=$(curl -s https://api.github.com/repos/WMS-PF/WMS_LogixPro/commits/circleci-and-codedeploy-setup | jq -r '.sha')
            aws deploy create-deployment \
              --application-name Git_application \
              --deployment-group-name development_gropup \
              --file-exists-behavior OVERWRITE \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --github-location repository=WMS-PF/WMS_LogixPro,commitId=$COMMIT_ID
  codeDeploy3:
      executor: aws-cli/default
      steps:
        - checkout
        - run: aws configure set aws_access_key_id $AWSJ_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWJ_SECRET_ACCESS_KEY && aws configure set default.region $AWS_REGION
        - run: |
            COMMIT_ID=$(curl -s https://api.github.com/repos/WMS-PF/WMS_LogixPro/commits/circleci-and-codedeploy-setup | jq -r '.sha')
            aws deploy create-deployment \
              --application-name github \
              --deployment-group-name github_auto \
              --file-exists-behavior OVERWRITE \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --github-location repository=WMS-PF/WMS_LogixPro,commitId=$COMMIT_ID
  codeDeploy4:
      executor: aws-cli/default
      steps:
        - checkout
        - aws-cli/setup:
            profile-name: nayelio
            aws-access-key-id: AWSN_ACCESS_KEY_ID
            aws-secret-access-key: AWSN_SECRET_ACCESS_KEY
        - run: |
            COMMIT_ID=$(curl -s https://api.github.com/repos/WMS-PF/WMS_LogixPro/commits/circleci-and-codedeploy-setup | jq -r '.sha')
            aws deploy create-deployment \
              --application-name Nayeli_EC \
              --deployment-group-name EC2Nayeli_DG \
              --file-exists-behavior OVERWRITE \
              --deployment-config-name CodeDeployDefault.OneAtATime \
              --github-location repository=WMS-PF/WMS_LogixPro,commitId=$COMMIT_ID
    

workflows:
  EC2-Deploy:
    jobs:
      - codeDeploy
      - codeDeploy2
      - codeDeploy3
      - codeDeploy4