version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@3.0.0
  aws-cli: circleci/aws-cli@3.1.5
  

jobs:
  beforeDeploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: ubuntu
      - run: npm install && npx next build
      - persist_to_workspace:
          root: .
          paths:
            - .
  Deploy:
    machine:
        image: ubuntu-2204:2023.04.2
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync . s3://logixpro-wms
    

workflows:
  EC2-Deploy:
    jobs:
      - beforeDeploy
      - Deploy:
          requires:
            - beforeDeploy